### ISSUE TITLE
Q: What is the difference between fs.sync.readfile and fs.readfile.sync?

### ISSUE THREAD

**Issue by jwthomp** [goodeggs/fibrous#28]
In reviewing the documentation I've seen examples where sync appears before the method, and other times afterward. It's unclear to me what the difference is and when you might use one vs. the other. Any explanation would be greatly appreciated.
- Jeff

**Comment by ide** [comment]
When you call `fs.sync.readFile`, `this` is `fs` inside of readFile. In this specific case the fs module doesn't reference `this` so either way works, but in general when you'd traditionally invoke a method using `obj.method(cb)` then you usually want `obj.sync.method()` with fibrous.
